services:

  db:
    container_name: pg_db
    image: postgres:16
    env_file:
      - db.env
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    env_file:
      - db.env
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - db

networks:
  postgres:

volumes:
  postgres:
