version: '3.12'

services:
    
    db:
      container_name: db_main
      restart: always
      image: postgres:16
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: steps_db
      volumes:
        - ./src/database/pgdata_main:/var/lib/postgresql/data
      
      ports:
        - 5432:5432
      
    db_test:
      container_name: db_test
      restart: always
      image: postgres:16
      environment:
        POSTGRES_USER: test_postgres
        POSTGRES_PASSWORD: test_postgres
        POSTGRES_DB: test_steps_db
      volumes:
        - ./src/database/pgdata_test:/var/lib/postgresql/data
      
      ports:
        - 5435:5432
