[project]
name = "steps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.14.1",
    "psycopg2-binary>=2.9.10",
    "pytest>=8.3.4",
    "sqlalchemy>=2.0.38",
]

[tool.pytest.ini_options]
testpaths = "tests/"
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
