[project]
name = "gh-steps"
version = "0.1.0"
description = "Благотворительный проект."
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.14.1",
    "fastapi[standard]>=0.115.8",
    "pydantic-settings>=2.8.0",
    "sqlalchemy>=2.0.38",
    "pytest>=8.3.4",
    "psycopg2-binary>=2.9.10",
]

[dependency-groups]
dev = [
    "ruff>=0.9.7",
]

[tool.ruff]
select = ["I", "UP", "B", "A"]
include = ["src/**/*.py"]

[tool.pytest.ini_options]
testpaths = "tests/"
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
